# Install scripts. (runs after repo cloning)
install:
  - npm install --force

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run build
  - npm run test

# Don't actually build.
build: off