# Install scripts. (runs after repo cloning)
install:
  # install modules
  - yarn install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - yarn run build
  - yarn run test

# Don't actually build.
build: off